サインアップ機能
shinonome-inc/backend-final-assignment-kake pull request #1
Opened 2024-08-26 08:23 UTC by immunity428

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-08-29 04:34 UTC, SShizawa approved these changes

2024-08-29 04:34 UTC, SShizawa commented on templates/accounts/signup.html
> +	{{ form.as_p }} ← formにはSignupFormのインスタンスが入っている。as_pとすることで、各input要素がpタグで囲まれた状態で表示される。
不必要な文章はコメントアウトするか、消しましょう

2024-08-29 04:34 UTC, SShizawa commented on accounts/admin.py
> +
現状であるとサインアップ機能のテストができていない状態です。
account/testのclass TestSignupViewの記述をしてください。

2024-08-31 09:46 UTC, SShizawa requested changes

2024-08-31 09:46 UTC, SShizawa commented on accounts/tests.py
> +class TestHomeView(TestCase):
TestHomeViewはtweets/test.pyに記述してください

2024-09-08 09:49 UTC, lokochaol commented on accounts/__init__.py
これも復活させた方がいいかと！

2024-09-09 09:12 UTC, immunity428 commented on accounts/__init__.py
復活させました！
ご指摘ありがとうございます。

2024-10-16 04:04 UTC, lokochaol approved these changes

2024-10-16 04:10 UTC, merged